[package]
name = "daily-knowledge"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
reqwest = "0.12.23"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
tokio-cron-scheduler = "0.14.0"
toml = "0.9.7"
